"""
SEOContent model.

Structured SEO data generated by the SEO agent (see
app/content/seo_service.py) - one row per SEO analysis, matching the
spec's field list exactly: primary/secondary keywords, search intent,
SEO title, meta description, URL slug, H1, H2 structure, internal linking
suggestions, image alt text, and hashtags.

Optionally linked to a Content row (content_id) when the SEO fields were
generated for a specific piece of content (e.g. a blog post); nullable so
SEO can also be generated standalone for a topic/page that doesn't have a
Content row yet - the spec's SEO Agent is a distinct capability from
content generation, not strictly dependent on it.

h2_structure and secondary_keywords/internal_linking_suggestions/hashtags
are lists - stored via the same StringList type BusinessProfile already
uses for its own string-array columns (Postgres ARRAY in production,
JSON-encoded text on SQLite for tests), rather than a JSON blob, since
these are genuinely homogeneous lists of short strings, not
heterogeneous structured objects the way CampaignStrategy's JSON columns
are.

No search-volume or ranking-probability field exists anywhere on this
model, deliberately - the spec is explicit that search-volume statistics
must never be invented without a verified data source, and no such data
source is wired into this app. Omitting the field entirely, rather than
adding a nullable one that's always null, keeps that constraint visible
in the schema itself rather than relying on every future caller to
remember not to populate it.
"""
from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base, TimestampMixin, UUIDPKMixin
from app.models.business_profile import StringList

if TYPE_CHECKING:
    from app.models.content import Content
    from app.models.organization import Organization


class SEOContent(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "seo_content"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    content_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("content_items.id", ondelete="CASCADE"),
        nullable=True,
        unique=True,
        index=True,
    )

    topic: Mapped[str] = mapped_column(String(500), nullable=False)

    primary_keyword: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    secondary_keywords: Mapped[Optional[list[str]]] = mapped_column(StringList, nullable=True)
    search_intent: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    seo_title: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    meta_description: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    url_slug: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    h1: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    h2_structure: Mapped[Optional[list[str]]] = mapped_column(StringList, nullable=True)
    internal_linking_suggestions: Mapped[Optional[list[str]]] = mapped_column(StringList, nullable=True)
    image_alt_text: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    hashtags: Mapped[Optional[list[str]]] = mapped_column(StringList, nullable=True)

    organization: Mapped["Organization"] = relationship("Organization")
    content: Mapped[Optional["Content"]] = relationship("Content", back_populates="seo")

    def __repr__(self) -> str:
        return f"<SEOContent {self.topic!r} org={self.organization_id}>"
